theme: jekyll-theme-cayman
title: Virtual Neuro Journal Club
<img src="https://github.com/giuliabaracc/Virtual-Neuroimaging-Journal-Club/blob/master/McGill.png" width="200"> <img src="https://github.com/giuliabaracc/Virtual-Neuroimaging-Journal-Club/blob/master/KI.png" width="200"> <img src="https://github.com/giuliabaracc/Virtual-Neuroimaging-Journal-Club/blob/master/UofT.png" width="200">

