theme: jekyll-theme-tactile
title: Virtual Neuroimaging Journal Club
description: In this space we will share our past, present and upcoming scheduled talks along with their corresponding Zoom recordings and PowerPoint slides!
